# Breakout: Merging and Saving Dataframes
The goal of this breakout is to give you practice merging `pandas` DataFrame objects using relational database logic.

# Merging

In [1]:
import pandas as pd
from pythonjsonlogger.core import merge_record_extra

left = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})
   
right = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                          'C': ['C0', 'C1', 'C2', 'C3'],
                          'D': ['D0', 'D1', 'D2', 'D3']})

In [2]:
left

  key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
3  K3  A3  B3

In [3]:
right

  key   C   D
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2
3  K3  C3  D3

Merge the dataframes `left` and `right` on their shared key.

In [4]:
df_merged = left.merge(right, on='key')
df_merged

  key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

In [5]:
left = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                        'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3']})
    
right = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                               'key2': ['K0', 'K0', 'K0', 'K0'],
                                  'C': ['C0', 'C1', 'C2', 'C3'],
                                  'D': ['D0', 'D1', 'D2', 'D3']})

In [6]:
left

  key1 key2   A   B
0   K0   K0  A0  B0
1   K0   K1  A1  B1
2   K1   K0  A2  B2
3   K2   K1  A3  B3

In [7]:
right

  key1 key2   C   D
0   K0   K0  C0  D0
1   K1   K0  C1  D1
2   K1   K0  C2  D2
3   K2   K0  C3  D3

Sometimes we will want to merge on more than one key. Try merging these two new dataframes by passing in a list of common keys to the `on` argument. Start with an inner join, and explain the output. Which values of `key1` and `key2` are retained? Which are dropped?

In [9]:
merged = left.merge(right, on=['key1', 'key2'])
merged

  key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2

Answer: The values of key1 and key2 that were retained are the combinations of both that are common to both 'left' and 'right'.

Now do the same thing, but with an outer join, left join, and right join. Discuss each.

In [10]:
merged_outer = left.merge(right, on=['key1', 'key2'], how='outer')
merged_outer

  key1 key2    A    B    C    D
0   K0   K0   A0   B0   C0   D0
1   K0   K1   A1   B1  NaN  NaN
2   K1   K0   A2   B2   C1   D1
3   K1   K0   A2   B2   C2   D2
4   K2   K0  NaN  NaN   C3   D3
5   K2   K1   A3   B3  NaN  NaN

Answer: outer join shows results of both tables regardless of key1/key2 common combinations

In [11]:
merged_left = left.merge(right, on=['key1', 'key2'], how='left')
merged_left

  key1 key2   A   B    C    D
0   K0   K0  A0  B0   C0   D0
1   K0   K1  A1  B1  NaN  NaN
2   K1   K0  A2  B2   C1   D1
3   K1   K0  A2  B2   C2   D2
4   K2   K1  A3  B3  NaN  NaN

Answer: left join shows all results of 'left' table with common combinations with 'right', and any key1/key2 values from 'left' that don't appear in 'right'

In [12]:
merged_right = left.merge(right, on=['key1', 'key2'], how='right')
merged_right

  key1 key2    A    B   C   D
0   K0   K0   A0   B0  C0  D0
1   K1   K0   A2   B2  C1  D1
2   K1   K0   A2   B2  C2  D2
3   K2   K0  NaN  NaN  C3  D3

Answer: right join shows all results of 'right' table with common combinations with 'left', and any key1/key2 values from 'right' that don't appear in 'left'

# Saving DataFrames
Save your most recent dataframe using the `.to_csv()` method. Open the resulting `.csv` to confirm that it looks like you expect.

In [13]:
merged_right.to_csv('../data/_merged_rightjoin_savedcsv.csv')