# Overview
This lecture will introduce some of the foundational tools that data scientists use to work with data in Python. We will focus primarily on `pandas`, a popular package for loading data, saving it, and all the manipulation that happens in between. Specifically, we will cover:
- Importing packages
- The `DataFrame` and `Series` objects in `pandas`
- Built-in helpers for dataframes
- Selecting and slicing data
- Merging data
- Parsing data from various formats
- Pandas alternatives

# Package imports
We experimented with package imports a bit last time to unlock `math` functionality. From now on we will rely heavily on Python's various packages to do data science work. Importing a package can follow a number of formats, but we'll stick to the canonical import statements.

To import `pandas`, simply put at the beginning of a python script (or in a notebook cell):

In [30]:
import pandas as pd

We can now access any functionality in the `pandas` package by doing `pd.function_name`. Some of the other packages we will use extensively are all imported in the cell below:

In [31]:
import numpy as np  # Numpy for most math, including linear algebra
import matplotlib.pyplot as plt  # Matplotlib for plotting

# For scikit-learn functionality, we will usually just import one class or function at a time as-needed
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestClassifier

If you get an error when trying to import any of those packages, you likely don't have it installed in your python environment. This can be solved by installing it with `pip`. For example:

In [32]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in C:\Users\vikra\dev\py_datascience_tut\.venv\Lib\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in C:\Users\vikra\dev\py_datascience_tut\.venv\Lib\site-packages (from scikit-learn) (2.4.6)
Requirement already satisfied: scipy>=1.10.0 in C:\Users\vikra\dev\py_datascience_tut\.venv\Lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in C:\Users\vikra\dev\py_datascience_tut\.venv\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in C:\Users\vikra\dev\py_datascience_tut\.venv\Lib\site-packages (from scikit-learn) (3.6.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

# Pandas

## DataFrame and Series objects
The best way to learn about pandas DataFrames and Series objects is to see an example. We'll load in a classic dataset of flower characteristics called the `iris` dataset. We'll use the `read_csv` functionality, which can load a CSV (comma separated value) file from either a web address or a filepath on your local machine.

In [33]:
df = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv')

This variable `df` is an instance of a pandas DataFrame, which you should think of as an object or class that contains lots of useful methods for working with data. Let's see what the dataframe looks like if we just print it out

In [34]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

Kind of like an Excel spreadsheet!  This makes sense, because we loaded the data from a csv file. There are 150 rows, numbered by the integers 0...149. This array of integers is called the DataFrame *index*, and we'll see shortly that the index doesn't have to be integers: it could be strings, or times, or anything really. But for now it is just a range of integer values, which we can look at explicitly using the `DataFrame.index` attribute.

In [35]:
print(df.index)

RangeIndex(start=0, stop=150, step=1)

The dataframe also has 5 columns, each with a column name. Now using the `DataFrame.columns` attribute:

In [36]:
print(df.columns)

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='str')

The indices and the column names just help us arrange and label our data, but the data can be viewed on its own using `df.values`:

In [37]:
df.values

array([[5.1, 3.5, 1.4, 0.2, 'setosa'],
       [4.9, 3.0, 1.4, 0.2, 'setosa'],
       [4.7, 3.2, 1.3, 0.2, 'setosa'],
       [4.6, 3.1, 1.5, 0.2, 'setosa'],
       [5.0, 3.6, 1.4, 0.2, 'setosa'],
       [5.4, 3.9, 1.7, 0.4, 'setosa'],
       [4.6, 3.4, 1.4, 0.3, 'setosa'],
       [5.0, 3.4, 1.5, 0.2, 'setosa'],
       [4.4, 2.9, 1.4, 0.2, 'setosa'],
       [4.9, 3.1, 1.5, 0.1, 'setosa'],
       [5.4, 3.7, 1.5, 0.2, 'setosa'],
       [4.8, 3.4, 1.6, 0.2, 'setosa'],
       [4.8, 3.0, 1.4, 0.1, 'setosa'],
       [4.3, 3.0, 1.1, 0.1, 'setosa'],
       [5.8, 4.0, 1.2, 0.2, 'setosa'],
       [5.7, 4.4, 1.5, 0.4, 'setosa'],
       [5.4, 3.9, 1.3, 0.4, 'setosa'],
       [5.1, 3.5, 1.4, 0.3, 'setosa'],
       [5.7, 3.8, 1.7, 0.3, 'setosa'],
       [5.1, 3.8, 1.5, 0.3, 'setosa'],
       [5.4, 3.4, 1.7, 0.2, 'setosa'],
       [5.1, 3.7, 1.5, 0.4, 'setosa'],
       [4.6, 3.6, 1.0, 0.2, 'setosa'],
       [5.1, 3.3, 1.7, 0.5, 'setosa'],
       [4.8, 3.4, 1.9, 0.2, 'setosa'],
       [5.0, 3.0, 1.6, 0.2, 'setosa'],
       [5.0, 3.4, 1.6, 0.4, 'setosa'],
       [5.2, 3.5, 1.5, 0.2, 'setosa'],
       [5.2, 3.4, 1.4, 0.2, 'setosa'],
       [4.7, 3.2, 1.6, 0.2, 'setosa'],
       [4.8, 3.1, 1.6, 0.2, 'setosa'],
       [5.4, 3.4, 1.5, 0.4, 'setosa'],
       [5.2, 4.1, 1.5, 0.1, 'setosa'],
       [5.5, 4.2, 1.4, 0.2, 'setosa'],
       [4.9, 3.1, 1.5, 0.2, 'setosa'],
       [5.0, 3.2, 1.2, 0.2, 'setosa'],
       [5.5, 3.5, 1.3, 0.2, 'setosa'],
       [4.9, 3.6, 1.4, 0.1, 'setosa'],
       [4.4, 3.0, 1.3, 0.2, 'setosa'],
       [5.1, 3.4, 1.5, 0.2, 'setosa'],
       [5.0, 3.5, 1.3, 0.3, 'setosa'],
       [4.5, 2.3, 1.3, 0.3, 'setosa'],
       [4.4, 3.2, 1.3, 0.2, 'setosa'],
       [5.0, 3.5, 1.6, 0.6, 'setosa'],
       [5.1, 3.8, 1.9, 0.4, 'setosa'],
       [4.8, 3.0, 1.4, 0.3, 'setosa'],
       [5.1, 3.8, 1.6, 0.2, 'setosa'],
       [4.6, 3.2, 1.4, 0.2, 'setosa'],
       [5.3, 3.7, 1.5, 0.2, 'setosa'],
       [5.0, 3.3, 1.4, 0.2, 'setosa'],
       [7.0, 3.2, 4.7, 1.4, 'versicolor'],
       [6.4, 3.2, 4.5, 1.5, 'versicolor'],
       [6.9, 3.1, 4.9, 1.5, 'versicolor'],
       [5.5, 2.3, 4.0, 1.3, 'versicolor'],
       [6.5, 2.8, 4.6, 1.5, 'versicolor'],
       [5.7, 2.8, 4.5, 1.3, 'versicolor'],
       [6.3, 3.3, 4.7, 1.6, 'versicolor'],
       [4.9, 2.4, 3.3, 1.0, 'versicolor'],
       [6.6, 2.9, 4.6, 1.3, 'versicolor'],
       [5.2, 2.7, 3.9, 1.4, 'versicolor'],
       [5.0, 2.0, 3.5, 1.0, 'versicolor'],
       [5.9, 3.0, 4.2, 1.5, 'versicolor'],
       [6.0, 2.2, 4.0, 1.0, 'versicolor'],
       [6.1, 2.9, 4.7, 1.4, 'versicolor'],
       [5.6, 2.9, 3.6, 1.3, 'versicolor'],
       [6.7, 3.1, 4.4, 1.4, 'versicolor'],
       [5.6, 3.0, 4.5, 1.5, 'versicolor'],
       [5.8, 2.7, 4.1, 1.0, 'versicolor'],
       [6.2, 2.2, 4.5, 1.5, 'versicolor'],
       [5.6, 2.5, 3.9, 1.1, 'versicolor'],
       [5.9, 3.2, 4.8, 1.8, 'versicolor'],
       [6.1, 2.8, 4.0, 1.3, 'versicolor'],
       [6.3, 2.5, 4.9, 1.5, 'versicolor'],
       [6.1, 2.8, 4.7, 1.2, 'versicolor'],
       [6.4, 2.9, 4.3, 1.3, 'versicolor'],
       [6.6, 3.0, 4.4, 1.4, 'versicolor'],
       [6.8, 2.8, 4.8, 1.4, 'versicolor'],
       [6.7, 3.0, 5.0, 1.7, 'versicolor'],
       [6.0, 2.9, 4.5, 1.5, 'versicolor'],
       [5.7, 2.6, 3.5, 1.0, 'versicolor'],
       [5.5, 2.4, 3.8, 1.1, 'versicolor'],
       [5.5, 2.4, 3.7, 1.0, 'versicolor'],
       [5.8, 2.7, 3.9, 1.2, 'versicolor'],
       [6.0, 2.7, 5.1, 1.6, 'versicolor'],
       [5.4, 3.0, 4.5, 1.5, 'versicolor'],
       [6.0, 3.4, 4.5, 1.6, 'versicolor'],
       [6.7, 3.1, 4.7, 1.5, 'versicolor'],
       [6.3, 2.3, 4.4, 1.3, 'versicolor'],
       [5.6, 3.0, 4.1, 1.3, 'versicolor'],
       [5.5, 2.5, 4.0, 1.3, 'versicolor'],
       [5.5, 2.6, 4.4, 1.2, 'versicolor'],
       [6.1, 3.0, 4.6, 1.4, 'versicolor'],
       [5.8, 2.6, 4.0, 1.2, 'versicolor'],
       [5.0, 2.3, 3.3, 1.0, 'versicolor'],
       [5.6, 2.7, 4.2, 1.3, 'versicolor'],
       [5.7, 3.0, 4.2, 1.2, 'versicolor'],
       [5.7, 2.9, 4.2, 1.3, 'versicolor'],
       [6.2, 2.9, 4.3, 1.3, 'versicolor'],
       [5.1, 2.5, 3.0, 1.1, 'versicolor'],
       [5.7, 2.8, 4.1, 1.3, 'versicolor'],
       [6.3, 3.3, 6.0, 2.5, 'virginica'],
       [5.8, 2.7, 5.1, 1.9, 'virginica'],
       [7.1, 3.0, 5.9, 2.1, 'virginica'],
       [6.3, 2.9, 5.6, 1.8, 'virginica'],
       [6.5, 3.0, 5.8, 2.2, 'virginica'],
       [7.6, 3.0, 6.6, 2.1, 'virginica'],
       [4.9, 2.5, 4.5, 1.7, 'virginica'],
       [7.3, 2.9, 6.3, 1.8, 'virginica'],
       [6.7, 2.5, 5.8, 1.8, 'virginica'],
       [7.2, 3.6, 6.1, 2.5, 'virginica'],
       [6.5, 3.2, 5.1, 2.0, 'virginica'],
       [6.4, 2.7, 5.3, 1.9, 'virginica'],
       [6.8, 3.0, 5.5, 2.1, 'virginica'],
       [5.7, 2.5, 5.0, 2.0, 'virginica'],
       [5.8, 2.8, 5.1, 2.4, 'virginica'],
       [6.4, 3.2, 5.3, 2.3, 'virginica'],
       [6.5, 3.0, 5.5, 1.8, 'virginica'],
       [7.7, 3.8, 6.7, 2.2, 'virginica'],
       [7.7, 2.6, 6.9, 2.3, 'virginica'],
       [6.0, 2.2, 5.0, 1.5, 'virginica'],
       [6.9, 3.2, 5.7, 2.3, 'virginica'],
       [5.6, 2.8, 4.9, 2.0, 'virginica'],
       [7.7, 2.8, 6.7, 2.0, 'virginica'],
       [6.3, 2.7, 4.9, 1.8, 'virginica'],
       [6.7, 3.3, 5.7, 2.1, 'virginica'],
       [7.2, 3.2, 6.0, 1.8, 'virginica'],
       [6.2, 2.8, 4.8, 1.8, 'virginica'],
       [6.1, 3.0, 4.9, 1.8, 'virginica'],
       [6.4, 2.8, 5.6, 2.1, 'virginica'],
       [7.2, 3.0, 5.8, 1.6, 'virginica'],
       [7.4, 2.8, 6.1, 1.9, 'virginica'],
       [7.9, 3.8, 6.4, 2.0, 'virginica'],
       [6.4, 2.8, 5.6, 2.2, 'virginica'],
       [6.3, 2.8, 5.1, 1.5, 'virginica'],
       [6.1, 2.6, 5.6, 1.4, 'virginica'],
       [7.7, 3.0, 6.1, 2.3, 'virginica'],
       [6.3, 3.4, 5.6, 2.4, 'virginica'],
       [6.4, 3.1, 5.5, 1.8, 'virginica'],
       [6.0, 3.0, 4.8, 1.8, 'virginica'],
       [6.9, 3.1, 5.4, 2.1, 'virginica'],
       [6.7, 3.1, 5.6, 2.4, 'virginica'],
       [6.9, 3.1, 5.1, 2.3, 'virginica'],
       [5.8, 2.7, 5.1, 1.9, 'virginica'],
       [6.8, 3.2, 5.9, 2.3, 'virginica'],
       [6.7, 3.3, 5.7, 2.5, 'virginica'],
       [6.7, 3.0, 5.2, 2.3, 'virginica'],
       [6.3, 2.5, 5.0, 1.9, 'virginica'],
       [6.5, 3.0, 5.2, 2.0, 'virginica'],
       [6.2, 3.4, 5.4, 2.3, 'virginica'],
       [5.9, 3.0, 5.1, 1.8, 'virginica']], dtype=object)

What data type is this array?

In [38]:
type(df.values)

numpy.ndarray

Turns out that under the hood, `pandas` stores data in Numpy `ndarrays`, an N-dimensional object that can store an arbitrary number of values. Numpy is a package that basically gives Python all the functionality of MATLAB, and Numpy arrays are one of the standard types that data scientists use to store and perform calculations on data in Python. We'll practice using them throughout this course, especially when we get to the Linear Algebra and Vector Calculus material.

### DataFrame helpers

There are [tons of functions and attributes](https://pandas.pydata.org/pandas-docs/stable/reference/frame.html) tacked onto the DataFrame object. We'll just demonstrate a few of the most common ones here.

The standard way to take a quick look at a dataframe is to use the following methods, which print out the first 5 rows (the head) and the last 5 rows (the tail) of the dataframe:

In [39]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [40]:
df.tail()

     sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

We can also look at the dataframe shape and its data types:

In [41]:
df.shape  # (rows, cols)

(150, 5)

In [42]:
df.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species             str
dtype: object

We can look at summary info, which includes most of the things we have printed out individually, plus a count of the non-null entries

In [43]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    str
dtypes: float64(4), str(1)
memory usage: 6.0 KB

And we can calculate statistics to get a baseline sense of what the numerical data looks like. Note that the `species` column is dropped in the output, because it is non-numeric.

In [44]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

groupby() allows you to group the dataframe by values of one of the columns:

In [45]:
df.groupby("species").describe()

           sepal_length                                              \
                  count   mean       std  min    25%  50%  75%  max
species
setosa             50.0  5.006  0.352490  4.3  4.800  5.0  5.2  5.8
versicolor         50.0  5.936  0.516171  4.9  5.600  5.9  6.3  7.0
virginica          50.0  6.588  0.635880  4.9  6.225  6.5  6.9  7.9

           sepal_width         ... petal_length      petal_width         \
                 count   mean  ...          75%  max       count   mean
species                        ...
setosa            50.0  3.428  ...        1.575  1.9        50.0  0.246
versicolor        50.0  2.770  ...        4.600  5.1        50.0  1.326
virginica         50.0  2.974  ...        5.875  6.9        50.0  2.026


                 std  min  25%  50%  75%  max
species
setosa      0.105386  0.1  0.2  0.2  0.3  0.6
versicolor  0.197753  1.0  1.2  1.3  1.5  1.8
virginica   0.274650  1.4  1.8  2.0  2.3  2.5

[3 rows x 32 columns]

### Accessing and Slicing DataFrames
The most common operation you will do with datasets is slice them up. Extract some portion you are interested in, get rid of a portion you aren't interested in, use part of the data for training a model, and another part for testing the model, etc. Pandas has a couple ways of helping you do this.

First, let's say you just want to get a single column. You can access that with square brackets and the column name:

In [46]:
sepal_width = df["sepal_width"]

In [47]:
print(sepal_width)

0      3.5
1      3.0
2      3.2
3      3.1
4      3.6
      ...
145    3.0
146    2.5
147    3.0
148    3.4
149    3.0
Name: sepal_width, Length: 150, dtype: float64

In [48]:
type(sepal_width)

pandas.Series

As you can see, accessing the single column returned an object that is no longer a DataFrame. Instead it is a `Series`, which you can think of as a one-dimensional DataFrame. There are lots of methods that apply to Series objects but not to DataFrames (like really a lot -- see [the docs](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.html)). One of my favorites for demonstration purposes:

In [49]:
species_list = df["species"].unique()

In [50]:
species_list

<StringArray>
['setosa', 'versicolor', 'virginica']
Length: 3, dtype: str

What if we wanted to extract two columns, though? Instead of specifying a single string column name, we now pass a list of column names to the square brackets:

In [51]:
sepal_geom = df[["sepal_width", "sepal_length"]]

In [52]:
sepal_geom.head()

   sepal_width  sepal_length
0          3.5           5.1
1          3.0           4.9
2          3.2           4.7
3          3.1           4.6
4          3.6           5.0

In [53]:
type(sepal_geom)

pandas.DataFrame

This time it remained a DataFrame because we have more than one column. In both cases though, we retained the same index that the DataFrame had originally.

Much of the time though, we don't want to keep all of the indices. What if we just wanted indices 0...20? In that case we would use `df.loc`:

In [54]:
df20 = df.loc[:20]

In [55]:
df20

    sepal_length  sepal_width  petal_length  petal_width species
0            5.1          3.5           1.4          0.2  setosa
1            4.9          3.0           1.4          0.2  setosa
2            4.7          3.2           1.3          0.2  setosa
3            4.6          3.1           1.5          0.2  setosa
4            5.0          3.6           1.4          0.2  setosa
5            5.4          3.9           1.7          0.4  setosa
6            4.6          3.4           1.4          0.3  setosa
7            5.0          3.4           1.5          0.2  setosa
8            4.4          2.9           1.4          0.2  setosa
9            4.9          3.1           1.5          0.1  setosa
10           5.4          3.7           1.5          0.2  setosa
11           4.8          3.4           1.6          0.2  setosa
12           4.8          3.0           1.4          0.1  setosa
13           4.3          3.0           1.1          0.1  setosa
14           5.8          4.0           1.2          0.2  setosa
15           5.7          4.4           1.5          0.4  setosa
16           5.4          3.9           1.3          0.4  setosa
17           5.1          3.5           1.4          0.3  setosa
18           5.7          3.8           1.7          0.3  setosa
19           5.1          3.8           1.5          0.3  setosa
20           5.4          3.4           1.7          0.2  setosa

This worked a bit like list slicing, but with two differences. The obvious one is that index `20` is included in the output. When slicing a list with `[:20]` you only retain indices 0...19. The more subtle difference, which we can't tell from this example, is that when using `.loc[]`, you need to give it a range of the *DataFrame indices* to slice out, rather than a range of integer row numbers. In this case, those were the same thing, but we could easily have a dataframe where they are different.

In [56]:
df2 = pd.DataFrame(index=["a", "b", "c"], columns=["red", "green", "blue"], data=np.random.rand(3, 3))

In [57]:
df2

        red     green      blue
a  0.286984  0.572264  0.493061
b  0.087021  0.881105  0.137615
c  0.462289  0.618860  0.405028

What happens if we try to use `.loc[]` to extract the first two rows?

In [58]:
df2_2 = df2.loc[:1]  # This throws an error, because our indices are strings, not integers

TypeError: cannot do slice indexing on Index with these indexers [1] of type int

Instead, we need to give it the string names we want:

In [59]:
df2_2 = df2.loc[["a", "b"]]

In [60]:
df2_2

        red     green      blue
a  0.286984  0.572264  0.493061
b  0.087021  0.881105  0.137615

We can also combine row access with column access to pull out certain row-column combinations:

In [61]:
df2_2gb = df2.loc[["a", "b"], ["green", "blue"]]

In [62]:
df2_2gb

      green      blue
a  0.572264  0.493061
b  0.881105  0.137615

Sometimes though, we just want to treat the dataframe like an n-dimensional array or list and access its contents purely using integer row and column numbers. Pandas lets you do that, but you need to use `.iloc` instead of `.loc`:

In [63]:
df2_i = df2.iloc[:2, 1:]

In [64]:
df2_i

      green      blue
a  0.572264  0.493061
b  0.881105  0.137615

We've produced the same output, but from a different point of view. Instead of telling pandas to return specific index and column *names* (which is what `loc` is for), we told pandas to return specific row and column *numbers* (which is what `iloc` is for). You'll probably find yourself using each in different circumstances; just be careful you don't mix them up! Because they expect different inputs, and produce different outputs.

### Breakout: Slicing Dataframes

### Merging DataFrames
Oftentimes you will want to combine data from two or more dataframes into a single dataframe. This operation is often called "merging" or "joining" datasets. In pandas, the methods for this rely on logic originally developed for relational database languages like SQL, so if you are familiar with database queries then this section should look familiar.

In [65]:
# Dataframes of measurements on certain days
df1 = pd.DataFrame({'day':[1, 2, 3, 4, 5], 'meas':[0.1, 0.2, 0.3, 0.4, 0.5 ]})
df2 = pd.DataFrame({'day':[1, 3, 5, 7], 'meas':[1.1, 1.3, 1.5, 1.7]})

In [66]:
df1

   day  meas
0    1   0.1
1    2   0.2
2    3   0.3
3    4   0.4
4    5   0.5

In [67]:
df2

   day  meas
0    1   1.1
1    3   1.3
2    5   1.5
3    7   1.7

When we join two dataframes, there are two basic parameters we need to specify:
- The key, which is specified with the `on` parameter. This should be a shared column or index name (or list of names) between the two dataframes, and is often the independent variable (e.g., time in a time series dataset so that you can match different measurements to the same time basis). If the key you want is named something different in the left and right dataframes, you can use `left_on` and `right_on` for their respective names. 
- The join method, which is specified with the `how` parameter. See [the docs](https://pandas.pydata.org/docs/reference/api/pandas.merge.html) for all your options here, but basically this specifies which dataframe(s) we use in order to create our new merged key.

For this example, we will merge on the `day` key and specify a `left` join, which means that `df1['day']` will end up being the day column in the output dataframe (if we do `df2.merge(df1, ...)` then `df2` becomes the left dataframe). The measurements from both dataframes will get attached to those `df1.day` values, but will be `NaN` if there wasn't one in the source dataframe.

In [68]:
df_out = df1.merge(df2, on = 'day', how = 'left')

In [69]:
df_out

   day  meas_x  meas_y
0    1     0.1     1.1
1    2     0.2     NaN
2    3     0.3     1.3
3    4     0.4     NaN
4    5     0.5     1.5

Conversely, we could do a right join, which makes the `day` column from `df2` our output day column.

In [70]:
df_out = df1.merge(df2, on = 'day', how = 'right')

In [71]:
df_out

   day  meas_x  meas_y
0    1     0.1     1.1
1    3     0.3     1.3
2    5     0.5     1.5
3    7     NaN     1.7

In each of the above cases, we lost some information. If we wanted to preserve all of the days from either dataframe, we could do an `outer` join. Then the resulting keys are the *union* of the keys from `df1` and `df2`:

In [72]:
df_out = df1.merge(df2, on = 'day', how = 'outer')

In [73]:
df_out

   day  meas_x  meas_y
0    1     0.1     1.1
1    2     0.2     NaN
2    3     0.3     1.3
3    4     0.4     NaN
4    5     0.5     1.5
5    7     NaN     1.7

If we don't specify anything, then we do an `inner` join by default. In that case, the keys are the *intersection* of the keys from `df1` and `df2`, i.e., the common keys that they both share:

In [74]:
df_out = df1.merge(df2, on = 'day')  # Same as df1.merge(df2, on="day", how="inner")

In [75]:
df_out

   day  meas_x  meas_y
0    1     0.1     1.1
1    3     0.3     1.3
2    5     0.5     1.5

### Saving DataFrames
Once we have a dataframe that we might want to use for future analysis, we usually want to save it somewhere. This can be done with the following statement.

In [76]:
 # We don't usually want to save the dataframe index as a column, but remove that if you do want to
df_out.to_csv("filepath.csv", index=False)

### Breakout: Merging DataFrames

# Parsing Data
In a perfect world, all the data we want to use is stored in a format that can be loaded into `pandas` with one simple line of code like `pd.read_csv("filename.csv")`. Unfortunately, loading data is usually more complicated than that. Datasets can have all sorts of issues: inconsistent labels, spacing, and separators are all common, and oftentimes you need to combine data from different formats. This section will cover some of the common "gotchas" with loading data from both local and web-based sources.

## Text and CSVs
If you are reading text data (e.g., from a `.txt` file) or CSV data (e.g., from a `.csv` file), `pd.read_csv` is probably the function you want to use. Please spend 5 minutes [reading the function documentation page](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html) to gain an appreciation for how complicated and flexible this function is. Once you are done, I will highlight just a few of the common problems you might encounter while parsing files and the `read_csv` arguments you need to fix them.

In [77]:
import pandas as pd

In [78]:
df = pd.read_csv("../data/sample_dataset.txt")

In [79]:
df

                                    Sample Data File
0  battery_voltage\trelative_humidity\tair_temper...
1  4.04\t15.2\t19.5\t0.22\t-0.15\t19.22046667\t16...
2  4.04\t15.15\t19.65\t0.2\t-0.12\t19.21\t1693700400
3   4.03\t15.55\t19.55\t0.2\t-0.2\t19.24\t1693701600
4  4.038037508\t15.91168788\t19.50981246\t0.21607...
5  4.03\t16.09\t19.4375\t0.2\t-0.12\t19.26\t16937...
6  4.031673173\t16.40863915\t19.39175125\t0.20334...
7  4.038365867\t16.72319576\t19.47875627\t0.21673...
8  4.03 16.65625 19.40125 0.2 -0.12 19.275 169370...
9  4.03\tNotANumber\t19.45625\t0.2\t-0.12\t19.255...

### Misplaced or missing header
Looking at the data file, we see there is a title at the top and then some whitespace. We don't want any of that:

In [80]:
df = pd.read_csv("../data/sample_dataset.txt", skiprows=2)

In [81]:
df

  battery_voltage\trelative_humidity\tair_temperature\tsolar_voltage\tbattery_power\tsea_surface_temperature\tepoch
0  4.04\t15.2\t19.5\t0.22\t-0.15\t19.22046667\t16...
1  4.04\t15.15\t19.65\t0.2\t-0.12\t19.21\t1693700400
2   4.03\t15.55\t19.55\t0.2\t-0.2\t19.24\t1693701600
3  4.038037508\t15.91168788\t19.50981246\t0.21607...
4  4.03\t16.09\t19.4375\t0.2\t-0.12\t19.26\t16937...
5  4.031673173\t16.40863915\t19.39175125\t0.20334...
6  4.038365867\t16.72319576\t19.47875627\t0.21673...
7  4.03 16.65625 19.40125 0.2 -0.12 19.275 169370...
8  4.03\tNotANumber\t19.45625\t0.2\t-0.12\t19.255...

### Non-comma delimiter
It looks a bit better now because at least the column names are not in the DataFrame values. But the tab delimiter/seperator (`\t`) is not being recognized as a delimiter. Let's fix that:

In [82]:
df = pd.read_csv("../data/sample_dataset.txt", skiprows=2, sep="\t")

ParserError: Error tokenizing data. C error: Expected 7 fields in line 11, saw 8

### Extra fields or general failure on one row
Whoops! The error message is telling us that we have an extra field in line 11 of the file. Let's just skip that bad line:

In [83]:
df = pd.read_csv("../data/sample_dataset.txt", skiprows=2, sep="\t", on_bad_lines="skip")

In [84]:
df

,battery_voltage,relative_humidity,air_temperature,solar_voltage,battery_power,sea_surface_temperature,epoch
0,4.04,15.2,19.500000,0.220000,-0.150000,19.220467,1.693699e+09
1,4.04,15.15,19.650000,0.200000,-0.120000,19.210000,1.693700e+09
2,4.03,15.55,19.550000,0.200000,-0.200000,19.240000,1.693702e+09
3,4.038037508,15.91168788,19.509812,0.216075,-0.159812,19.248038,1.693703e+09
4,4.03,16.09,19.437500,0.200000,-0.120000,19.260000,1.693704e+09
5,4.031673173,16.40863915,19.391751,0.203346,-0.125020,19.264980,1.693705e+09
6,4.03 16.65625 19.40125 0.2 -0.12 19.275 169370...,NaN,NaN,NaN,NaN,NaN,NaN
7,4.03,NotANumber,19.456250,0.200000,-0.120000,19.255000,1.693709e+09

### Inconsistent delimiter
One of the rows actually has spaces as a delimiter rather than tabs, so there is technically no delimiter in that row. To handle this more general case, we use the following more general seperator, which is a [regex](https://en.wikipedia.org/wiki/Regular_expression) string:

In [85]:
df = pd.read_csv("../data/sample_dataset.txt", skiprows=2, sep=r"\s+", on_bad_lines="skip")

In [86]:
df

,battery_voltage,relative_humidity,air_temperature,solar_voltage,battery_power,sea_surface_temperature,epoch
0,4.040000,15.2,19.500000,0.220000,-0.150000,19.220467,1693699200
1,4.040000,15.15,19.650000,0.200000,-0.120000,19.210000,1693700400
2,4.030000,15.55,19.550000,0.200000,-0.200000,19.240000,1693701600
3,4.038038,15.91168788,19.509812,0.216075,-0.159812,19.248038,1693702800
4,4.030000,16.09,19.437500,0.200000,-0.120000,19.260000,1693704000
5,4.031673,16.40863915,19.391751,0.203346,-0.125020,19.264980,1693705200
6,4.030000,16.65625,19.401250,0.200000,-0.120000,19.275000,1693707600
7,4.030000,NotANumber,19.456250,0.200000,-0.120000,19.255000,1693708800

### Weird null values
One of the values is being read in as the string `NotANumber` which is a non-standard way of representing a NaN value. If we want to actually encode this as a numpy `NaN` so that, for example, we can still treat that column as an array of floats, we would need to specify this NaN indicator

In [87]:
df = pd.read_csv("../data/sample_dataset.txt", skiprows=2, sep=r"\s+", on_bad_lines="skip", na_values=["NotANumber"])

In [88]:
df

,battery_voltage,relative_humidity,air_temperature,solar_voltage,battery_power,sea_surface_temperature,epoch
0,4.040000,15.200000,19.500000,0.220000,-0.150000,19.220467,1693699200
1,4.040000,15.150000,19.650000,0.200000,-0.120000,19.210000,1693700400
2,4.030000,15.550000,19.550000,0.200000,-0.200000,19.240000,1693701600
3,4.038038,15.911688,19.509812,0.216075,-0.159812,19.248038,1693702800
4,4.030000,16.090000,19.437500,0.200000,-0.120000,19.260000,1693704000
5,4.031673,16.408639,19.391751,0.203346,-0.125020,19.264980,1693705200
6,4.030000,16.656250,19.401250,0.200000,-0.120000,19.275000,1693707600
7,4.030000,NaN,19.456250,0.200000,-0.120000,19.255000,1693708800

## Web Data and the JSON format
Not all data comes from `.csv` files. Most likely, much of the data you will end up working with as data scientists will come from the internet -- either the public internet, or via API calls to internal endpoints that the software engineers at your company set up. The easiest way to bring this data into Python is via the `requests` module, which allows you to load [json data](https://en.wikipedia.org/wiki/JSON) into a Python dictionary, which can then be used as-is or further converted into a DataFrame.

The `requests` module allows us to send HTTP requests from python. There are [different types of HTTP requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods). Some allow you to `GET` data, others allow you to `POST` data. We'll just demonstrate the `GET` method by requesting data from a free Pokemon API

In [89]:
import requests
pokemon_name = "pikachu"
url = f"https://pokeapi.co/api/v2/pokemon/{pokemon_name}"
response = requests.get(url)

What does the response look like?

In [90]:
response

This is just a response code (see [list here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status)), indicating that we succesfully received the data. But where is the actual data?

In [91]:
data = response.json()

In [ ]:
# data

Lots of data stored as a python dictionary. We can take a look at the keys for a more compact view:

In [92]:
data.keys()

dict_keys(['abilities', 'base_experience', 'cries', 'forms', 'game_indices', 'height', 'held_items', 'id', 'is_default', 'location_area_encounters', 'moves', 'name', 'order', 'past_abilities', 'past_stats', 'past_types', 'species', 'sprites', 'stats', 'types', 'weight'])

In [93]:
data["types"]

[{'slot': 1,
  'type': {'name': 'electric', 'url': 'https://pokeapi.co/api/v2/type/13/'}}]

We can't turn the whole thing into a pandas dataframe without further manipulation, but we can extract some of the lists of dictionaries it contains to dataframes:

In [94]:
data["stats"]

[{'base_stat': 35,
  'effort': 0,
  'stat': {'name': 'hp', 'url': 'https://pokeapi.co/api/v2/stat/1/'}},
 {'base_stat': 55,
  'effort': 0,
  'stat': {'name': 'attack', 'url': 'https://pokeapi.co/api/v2/stat/2/'}},
 {'base_stat': 40,
  'effort': 0,
  'stat': {'name': 'defense', 'url': 'https://pokeapi.co/api/v2/stat/3/'}},
 {'base_stat': 50,
  'effort': 0,
  'stat': {'name': 'special-attack',
   'url': 'https://pokeapi.co/api/v2/stat/4/'}},
 {'base_stat': 50,
  'effort': 0,
  'stat': {'name': 'special-defense',
   'url': 'https://pokeapi.co/api/v2/stat/5/'}},
 {'base_stat': 90,
  'effort': 2,
  'stat': {'name': 'speed', 'url': 'https://pokeapi.co/api/v2/stat/6/'}}]

In [95]:
df = pd.DataFrame(data=data["stats"])

In [96]:
df

   base_stat  effort                                               stat
0         35       0  {'name': 'hp', 'url': 'https://pokeapi.co/api/...
1         55       0  {'name': 'attack', 'url': 'https://pokeapi.co/...
2         40       0  {'name': 'defense', 'url': 'https://pokeapi.co...
3         50       0  {'name': 'special-attack', 'url': 'https://pok...
4         50       0  {'name': 'special-defense', 'url': 'https://po...
5         90       2  {'name': 'speed', 'url': 'https://pokeapi.co/a...

# Pandas Alternatives
In this class we will use `pandas` exclusively, because it is the mostly widely used package for data manipulation. But there are alternatives that you should be aware of.

## R
`pandas` is basically Python's answer to the R `data.frame` type. If you don't like Python, or you work at a company that predominantly uses R, then you will find that it has all of the functionality of `pandas` and more. It is especially helpful if you are doing statistics-focused work, because it has built-in functionality that either doesn't exist in Python or requires tedious Python package management. On the downside, R is less of a general-purpose programming language than Python -- it would either be a pain or impossible to build your full software stack in R, because that is not what it's designed for. You probably don't want Python for your full stack either, but you could at least do it and it would be less painful

## Polars
`polars` is a Python package that is becoming increasingly popular. It is similar to `pandas` in a lot of ways (note the bear theme in the name), but it boasts significant efficiency gains, especially when dealing with large amounts of data. You are welcome to explore it and even use it for assignments in this class, but we won't be learning any of the syntax.